
name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Berlin
          plugin_introduction: yes
          plugin_introduction_title: "About me"
          # Reaktionen
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage
          # Languages
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot, javascript, lua, swift, tqsl
          plugin_languages_sections: most-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 365
          # Calendar
          plugin_calendar: yes
          plugin_calendar_limit: 0
          # Topics          
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
